### ISSUE TITLE
Build Server

### ISSUE THREAD

**Issue by persn** [LateStartStudio/Hero6#12]
It would really help if we had a build server for CI builds, automation of release builds, etc.

**Comment by persn** [comment]
We have a basic build server in place, although some basics are still missing

1. One build config is always failing, WindowsDX Release. It has something to do with WiX.
2. Automated build for Pull Requests, so that we can see if the build is successful before merge.
3. Build configs for master branch?
4. Deploy Windows Release.

**Comment by robertkety** [comment]
Automated builds for pull requests are not possible through TFS at this time.  We're considering Travis and/or Jenkins as a temporary solution or permanent replacement.
Tests run automatically as part of the build definition.  The build step is already there - it just needs to be activated.

**Comment by robertkety** [comment]
Automated builds for pull requests are now possible in TFS.  I activated that feature for our builds last night.

**Comment by persn** [comment]
I updated the checklist to contain the hook thing. It's great that it's building on pull requests now, but actual visual feedback directly on GitHub should be considered a part of the basic features we want.

Not sure how to go about doing that however, the workaround in the post by Eric [here](http://stackoverflow.com/questions/41081171/trigger-visual-studio-team-services-build-for-a-github-pull-request) sounds a little icky

**Comment by persn** [comment]
This is very outdated and we're using TeamCity now so I'll close
