### ISSUE TITLE
[UI - SierraVGA] Extension bar buttons, lighter button on mouse over

### ISSUE THREAD

**Issue by persn** [LateStartStudio/Hero6#182]
On our Verb bar our buttons become much lighter on mouse over, however the extension bar which is visually the same does not have this feature. There should be some aesthetic distinction on mouse over for all the buttons, and it should match the same feature on the verb bar.

![2017-05-04 1](https://cloud.githubusercontent.com/assets/1510803/25715882/57925ea0-30fd-11e7-8308-91ca7d5a9b34.png)

**Comment by robertkety** [comment]
#190

**Comment by persn** [comment]
Here's a little GitHub trick for ya I learned recently. Instead of updating the issue when uploading the Pull Request. Put something like "Fixes #190 " in the first post of the pull request, or even in the commit message. This issue will be updated with a reference automatically, and also automatically close when the Pull Request is accepted. https://help.github.com/articles/closing-issues-via-commit-messages/
