### ISSUE TITLE
[UI - SierraVGA] Distorted icons

### ISSUE THREAD

**Issue by persn** [LateStartStudio/Hero6#76]
The verb bar icons for looking and opening the sub bar menu are distorted, it's really obvious if you continuously move your mouse in and out on either of the icons. The reason for this is that each icon in the verb bar has a light and a dark alternative, where the light icon will display on mouse over, however for these two specific icons the image files doesn't match up with each other, they're significantly different, causing a distortion effect.

For the looking icon the the dark alternative doesn't match up with the rest of the verb bar, for the sub menu icon the light icon doesn't match. The easiest fix is possibly to take the dark looking icon and make it darker to match the rest of the verb bar, and the opposite for the sub menu icon.

There's also a possibility that I did something wrong when I imported the images over from the AGS demo

**Screenshot:**
![distortion](https://cloud.githubusercontent.com/assets/1510803/21651500/1eddc480-d2a9-11e6-9e05-ff0f5e49cad8.png)

**Look Icon:**
![look dark](https://cloud.githubusercontent.com/assets/1510803/21651209/15bb4b08-d2a8-11e6-8749-9f7dd14bae12.png) ![look light](https://cloud.githubusercontent.com/assets/1510803/21651210/15bce0b2-d2a8-11e6-9652-f6ae0f8e9e32.png)

**Sub Bar Menu Icon:**
![sub menu dark](https://cloud.githubusercontent.com/assets/1510803/21651234/26aae522-d2a8-11e6-873b-5b6ce990dc97.png) ![sub menu light](https://cloud.githubusercontent.com/assets/1510803/21651235/26aae5e0-d2a8-11e6-96dc-89cc91c63749.png)

**Comment by robertkety** [comment]
I've fixed these icon issues and am working on getting them into the branch

**Comment by persn** [comment]
Instead of the previous message you can just assign yourself to the issue. It tells the same message more or less and then people can see that someone called dibs while scrolling down the issues list.

**Comment by persn** [comment]
Fixed in #100
